TITLE = "GettingBetter Schema"
VERSION = "0.0.1"

[goal_1]
    [goal_1.system]
    name = "system_1"
    [goal_1.system.routines]
        routine_1 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_2 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_3 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]


[goal_2]
    [goal_2.system]
    name = "system_2"
    [goal_2.system.routines]
        routine_1 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_2 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_3 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]

[goal_3]
    [goal_3.system]
    name = "system_3"
    [goal_3.system.routines]
        routine_1 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_2 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_3 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]


