TITLE = "GettingBetter Schema"
VERSION = "0.0.2"

[system_1]
    goal = "goal_1"
    [system_1.routines]
        routine_1 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_2 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_3 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]


[system_2]
    goal = "goal_2"
    [system_2.routines]
        routine_1 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_2 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_3 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]

[system_3]
    goal = "goal_3"
    [system_3.routines]
        routine_1 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_2 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]
        routine_3 = [
            "task_1",
            "task_2",
            "task_3",
            "task_4"
        ]


